import "@/styles/globals.css";

import { Layout } from "@/templates/layout";

export const metadata = {
  title: 'Site.set',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
      </head>

      <body>
        <main>
          <Layout>
            {children}
          </Layout>
        </main>
      </body>
    </html>
  )
}
